package io.github.shad3n.predicatemapper;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import io.github.shad3n.predicatemapper.annotation.Op;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import java.io.IOException;
import java.util.List;

/**
 * Generates QueryDSL predicate implementations from {@code @io.github.shad3n.annotation.PredicateMapper} interfaces.
 */
class FilterImplementationGenerator {

    private static final String SPRING_COMPONENT = "org.springframework.stereotype.Component";

    private final ProcessingEnvironment processingEnv;

    /**
     * Constructs a new generator.
     *
     * @param processingEnv the annotation processing environment
     */
    public FilterImplementationGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Checks if Spring's Component annotation is available on the classpath.
     *
     * @return true if Spring is available, false otherwise
     */
    private boolean isSpringAvailable() {
        return processingEnv.getElementUtils().getTypeElement(SPRING_COMPONENT) != null;
    }

    /**
     * Generates the concrete implementation of the provided {@code @io.github.shad3n.annotation.PredicateMapper} interface.
     *
     * @param iface   the interface element for which to generate the implementation
     * @param methods the list of method mappings detailing the predicate generation logic
     * @throws IOException if writing the source file fails
     */
    public void generateImpl(TypeElement iface, List<MethodMapping> methods) throws IOException {
        ClassName ifaceName = ClassName.get(iface);
        String implName = iface.getSimpleName() + "Impl";

        TypeSpec.Builder classBuilder = createClassBuilder(ifaceName, implName);

        ClassName predicateName = ClassName.get("com.querydsl.core.types", "Predicate");
        ClassName booleanBuilderName = ClassName.get("com.querydsl.core", "BooleanBuilder");
        ClassName expressionsName = ClassName.get("com.querydsl.core.types.dsl", "Expressions");

        for (MethodMapping m : methods) {
            classBuilder.addMethod(generateMethod(m, predicateName, booleanBuilderName, expressionsName));
        }

        JavaFile javaFile = JavaFile.builder(ifaceName.packageName(), classBuilder.build())
                                    .indent("    ")
                                    .build();

        javaFile.writeTo(processingEnv.getFiler());
    }

    /**
     * Creates a type builder for the implementation class, ensuring it implements
     * the target interface. Adds @Component annotation only if Spring is available on the classpath.
     *
     * @param ifaceName the ClassName of the interface being implemented
     * @param implName  the name of the generated implementation class
     * @return a configured TypeSpec.Builder
     */
    private TypeSpec.Builder createClassBuilder(ClassName ifaceName, String implName) {
        TypeSpec.Builder builder = TypeSpec.classBuilder(implName)
                                           .addModifiers(Modifier.PUBLIC)
                                           .addSuperinterface(ifaceName)
                                           .addJavadoc("Generated by FilterToQueryDslApt — do not edit\n");

        if (isSpringAvailable()) {
            ClassName componentName = ClassName.get("org.springframework.stereotype", "Component");
            builder.addAnnotation(componentName);
        }

        return builder;
    }

    /**
     * Generates a concrete method spec based on the method mapping, configuring the boolean builder
     * and sequentially appending field-specific logic.
     *
     * @param m                  the method mapping containing the signature and field settings
     * @param predicateName      the class name representing the QueryDSL Predicate
     * @param booleanBuilderName the class name representing the QueryDSL BooleanBuilder
     * @param expressionsName    the class name representing the QueryDSL Expressions
     * @return the ready-to-build method specification
     */
    private MethodSpec generateMethod(MethodMapping m, ClassName predicateName, ClassName booleanBuilderName,
                                      ClassName expressionsName) {
        MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder(m.methodName())
                                                     .addAnnotation(Override.class)
                                                     .addModifiers(Modifier.PUBLIC)
                                                     .returns(predicateName)
                                                     .addParameter(m.dtoClass(), "dto");

        String qClassName = m.qClass().simpleName();
        String variableName = qClassName.startsWith("Q") ?
                Character.toLowerCase(qClassName.charAt(1)) + qClassName.substring(2) : "entity";
        methodBuilder.addStatement("$T q = new $T($S)", m.qClass(), m.qClass(), variableName);
        methodBuilder.addStatement("$T builder = new $T()", booleanBuilderName, booleanBuilderName);

        for (FieldMapping f : m.fields()) {
            generateFieldCondition(methodBuilder, f);
        }

        methodBuilder.addStatement("$T result = builder.getValue()", predicateName);
        methodBuilder.addStatement("return result != null ? result : $T.TRUE", expressionsName);

        return methodBuilder.build();
    }

    /**
     * Appends to a method builder the specific QueryDSL expressions testing a field's value.
     * Evaluates checking for null values versus equality, range comparisons, or like matching.
     *
     * @param methodBuilder the builder corresponding to the generated method
     * @param fieldMapping  the field mapping that describes the operation and target path
     */
    private void generateFieldCondition(MethodSpec.Builder methodBuilder, FieldMapping fieldMapping) {
        String dtoFieldName = fieldMapping.dtoFieldName();
        String getter = "dto.get" + capitalize(dtoFieldName) + "()";
        String qPath = "q." + fieldMapping.path();

        if (fieldMapping.op() == Op.IS_NULL) {
            methodBuilder.beginControlFlow("if ($T.TRUE.equals($L))", Boolean.class, getter)
                         .addStatement("builder.and($L.isNull())", qPath)
                         .endControlFlow();
        } else if (fieldMapping.op() == Op.IS_NOT_NULL) {
            methodBuilder.beginControlFlow("if ($T.TRUE.equals($L))", Boolean.class, getter)
                         .addStatement("builder.and($L.isNotNull())", qPath)
                         .endControlFlow();
        } else {
            String expr = switch (fieldMapping.op()) {
                case EQ -> qPath + ".eq(" + getter + ")";
                case NOT_EQ -> qPath + ".ne(" + getter + ")";
                case LTE -> qPath + ".loe(" + getter + ")";
                case GTE -> qPath + ".goe(" + getter + ")";
                case LIKE -> qPath + ".like(" + getter + ")";
                case IN -> qPath + ".in(" + getter + ")";
                default -> throw new IllegalStateException("Unhandled op: " + fieldMapping.op());
            };
            methodBuilder.beginControlFlow("if ($L != null)", getter)
                         .addStatement("builder.and($L)", expr)
                         .endControlFlow();
        }
    }

    /**
     * Capitalizes the first letter of the given string.
     *
     * @param s the string to capitalize
     * @return the capitalized string, or the original string if empty
     */
    private String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}