package io.github.shad3n.predicatemapper;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.TypeSpec;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates the implementation class of a {@code @PredicateMapper} interface, delegating each method to
 * the backend that maps it.
 */
class FilterImplementationGenerator {

    private static final String SPRING_COMPONENT = "org.springframework.stereotype.Component";

    private final ProcessingEnvironment processingEnv;

    /**
     * Constructs a new generator.
     *
     * @param processingEnv the annotation processing environment
     */
    public FilterImplementationGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Checks if Spring's Component annotation is available on the classpath.
     *
     * @return true if Spring is available, false otherwise
     */
    private boolean isSpringAvailable() {
        return processingEnv.getElementUtils().getTypeElement(SPRING_COMPONENT) != null;
    }

    /**
     * Generates the concrete implementation of the provided {@code @PredicateMapper} interface.
     *
     * @param iface   the interface element for which to generate the implementation
     * @param methods the list of method mappings detailing the predicate generation logic
     * @throws IOException if writing the source file fails
     */
    public void generateImpl(TypeElement iface, List<MethodMapping> methods) throws IOException {
        ClassName ifaceName = ClassName.get(iface);
        String implName = iface.getSimpleName() + "Impl";

        TypeSpec.Builder classBuilder = createClassBuilder(ifaceName, implName);

        methods.stream()
               .collect(Collectors.groupingBy(MethodMapping::backend, LinkedHashMap::new, Collectors.toList()))
               .forEach((backend, backendMethods) -> classBuilder.addMethods(backend.implement(backendMethods)));

        JavaFile javaFile = JavaFile.builder(ifaceName.packageName(), classBuilder.build())
                                    .indent("    ")
                                    .build();

        javaFile.writeTo(processingEnv.getFiler());
    }

    /**
     * Creates a type builder for the implementation class, ensuring it implements
     * the target interface. Adds @Component annotation only if Spring is available on the classpath.
     *
     * @param ifaceName the ClassName of the interface being implemented
     * @param implName  the name of the generated implementation class
     * @return a configured TypeSpec.Builder
     */
    private TypeSpec.Builder createClassBuilder(ClassName ifaceName, String implName) {
        TypeSpec.Builder builder = TypeSpec.classBuilder(implName)
                                           .addModifiers(Modifier.PUBLIC)
                                           .addSuperinterface(ifaceName)
                                           .addJavadoc("Generated by FilterToQueryDslApt — do not edit\n");

        if (isSpringAvailable()) {
            ClassName componentName = ClassName.get("org.springframework.stereotype", "Component");
            builder.addAnnotation(componentName);
        }

        return builder;
    }
}
